[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "liflidar"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
]

[tool.setuptools.packages.find]
include = ["liflidar"]

[tool.ruff]
line-length = 120
